export const tagIds = [
  // Ordering of Category tags in terms of importance is done here
  'categoryCdbd',
  'categoryRe',
  'categoryDoctrine',
  'categoryTopical',
  'doctrineFootwashing',
  'doctrineBaptism',
  'bookGenesis',
  'bookExodus',
  'bookLeviticus',
  'bookNumbers',
  'bookDeuteronomy',
  'bookJoshua',
  'bookJudges',
  'bookRuth',
  'book1samuel',
  'book2samuel',
  'book1kings',
  'book2kings',
  'book1chronicles',
  'book2chronicles',
  'bookEzra',
  'bookNehemiah',
  'bookEsther',
  'bookJob',
  'bookPsalms',
  'bookProverbs',
  'bookEcclesiastes',
  'bookSongofsolomon',
  'bookisaiah',
  'bookJeremiah',
  'bookLamentations',
  'bookEzekiel',
  'bookDaniel',
  'bookHosea',
  'bookJoel',
  'bookAmos',
  'bookObadiah',
  'bookJonah',
  'bookMicah',
  'bookNahum',
  'bookHabakkuk',
  'bookZephaniah',
  'bookHaggai',
  'bookZechariah',
  'bookMalachi',
  'bookMatthew',
  'bookMark',
  'bookLuke',
  'bookJohn',
  'bookActs',
  'bookRomans',
  'book1corinthians',
  'book2corinthians',
  'bookGalatians',
  'bookEphesians',
  'bookPhilippians',
  'bookColossians',
  'book1thessalonians',
  'book2thessalonians',
  'book1timothy',
  'book2timothy',
  'bookTitus',
  'bookPhilemon',
  'bookHebrews',
  'bookJames',
  'book1peter',
  'book2peter',
  'book1john',
  'book2john',
  'book3john',
  'bookJude',
  'bookRevelation',
] as const;

export type TagIds = (typeof tagIds)[number];

export type TagDetails =
  | {
      en: string;
      zh: string;
      slug: string;
      type: 'category' | 'doctrine' | 'theme';
    }
  | {
      en: string;
      zh: string;
      slug: string;
      type: 'bible';
      bookCategory: string;
    };

type TagDictionary = {
  [K in TagIds]: TagDetails;
};

export const tagDictionary: TagDictionary = {
  categoryTopical: {
    en: 'Topical',
    zh: '话题性',
    slug: 'topical',
    type: 'category',
  },
  categoryRe: {
    en: 'RE@Home',
    zh: '家庭宗教教育',
    slug: 're',
    type: 'category',
  },
  categoryDoctrine: {
    en: 'Doctrine',
    zh: '信条',
    slug: 'doctrine',
    type: 'category',
  },
  categoryCdbd: {
    en: 'CDBD',
    zh: '每日读经',
    slug: 'cdbd',
    type: 'category',
  },
  doctrineFootwashing: {
    en: 'Footwashing',
    zh: '洗脚礼',
    slug: 'footwashing',
    type: 'doctrine',
  },
  doctrineBaptism: {
    en: 'Baptism',
    zh: '洗礼',
    slug: 'baptism',
    type: 'doctrine',
  },
  bookGenesis: {
    en: 'Genesis',
    zh: '创世纪',
    bookCategory: 'Pentateuch',
    type: 'bible',
    slug: 'genesis',
  },
  bookExodus: {
    en: 'Exodus',
    zh: '出埃及记',
    bookCategory: 'Pentateuch',
    type: 'bible',
    slug: 'exodus',
  },
  bookLeviticus: {
    en: 'Leviticus',
    zh: '',
    bookCategory: 'Pentateuch',
    type: 'bible',
    slug: 'leviticus',
  },
  bookNumbers: {
    en: 'Numbers',
    zh: '',
    bookCategory: 'Pentateuch',
    type: 'bible',
    slug: 'numbers',
  },
  bookDeuteronomy: {
    en: 'Deuteronomy',
    zh: '',
    bookCategory: 'Pentateuch',
    type: 'bible',
    slug: 'deuteronomy',
  },
  bookJoshua: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'joshua',
  },
  bookJudges: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'judges',
  },
  bookRuth: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'ruth',
  },
  book1samuel: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-samuel',
  },
  book2samuel: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-samuel',
  },
  book1kings: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-kings',
  },
  book2kings: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-kings',
  },
  book1chronicles: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-chronicles',
  },
  book2chronicles: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-chronicles',
  },
  bookEzra: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'ezra',
  },
  bookNehemiah: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'nehemiah',
  },
  bookEsther: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'esther',
  },
  bookJob: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'job',
  },
  bookPsalms: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'psalms',
  },
  bookProverbs: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'proverbs',
  },
  bookEcclesiastes: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'ecclesiastes',
  },
  bookSongofsolomon: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'song-of-solomon',
  },
  bookisaiah: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'isaiah',
  },
  bookJeremiah: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'jeremiah',
  },
  bookLamentations: {
    en: 'Lamentations',
    zh: '耶利米哀歌',
    bookCategory: '',
    type: 'bible',
    slug: 'lamentations',
  },
  bookEzekiel: {
    en: 'Ezekiel',
    zh: '以西结书',
    bookCategory: '',
    type: 'bible',
    slug: 'ezekiel',
  },
  bookDaniel: {
    en: 'Daniel',
    zh: '但以理书',
    bookCategory: '',
    type: 'bible',
    slug: 'daniel',
  },
  bookHosea: {
    en: 'Hosea',
    zh: '何西阿书',
    bookCategory: '',
    type: 'bible',
    slug: 'hosea',
  },
  bookJoel: {
    en: 'Joel',
    zh: '约珥书',
    bookCategory: '',
    type: 'bible',
    slug: 'joel',
  },
  bookAmos: {
    en: 'Amos',
    zh: '阿摩司书',
    bookCategory: '',
    type: 'bible',
    slug: 'amos',
  },
  bookObadiah: {
    en: 'Obadiah',
    zh: '俄巴底亚书',
    bookCategory: '',
    type: 'bible',
    slug: 'obadiah',
  },
  bookJonah: {
    en: 'Jonah',
    zh: '约拿书',
    bookCategory: '',
    type: 'bible',
    slug: 'jonah',
  },
  bookMicah: {
    en: 'Micah',
    zh: '弥迦书',
    bookCategory: '',
    type: 'bible',
    slug: 'micah',
  },
  bookNahum: {
    en: 'Nahum',
    zh: '那鸿书',
    bookCategory: '',
    type: 'bible',
    slug: 'nahum',
  },
  bookHabakkuk: {
    en: 'Habakkuk',
    zh: '哈巴谷书',
    bookCategory: '',
    type: 'bible',
    slug: 'habakkuk',
  },
  bookZephaniah: {
    en: 'Zephaniah',
    zh: '西番雅书',
    bookCategory: '',
    type: 'bible',
    slug: 'zephaniah',
  },
  bookHaggai: {
    en: 'Haggai',
    zh: '哈该书',
    bookCategory: '',
    type: 'bible',
    slug: 'haggai',
  },
  bookZechariah: {
    en: 'Zechariah',
    zh: '撒迦利亚书',
    bookCategory: '',
    type: 'bible',
    slug: 'zechariah',
  },
  bookMalachi: {
    en: 'Malachi',
    zh: '玛拉基书',
    bookCategory: '',
    type: 'bible',
    slug: 'malachi',
  },
  bookMatthew: {
    en: 'Matthew',
    zh: '马太福音',
    bookCategory: 'Gospels',
    type: 'bible',
    slug: 'matthew',
  },
  bookMark: {
    en: 'Mark',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'mark',
  },
  bookLuke: {
    en: 'Luke',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'luke',
  },
  bookJohn: {
    en: 'John',
    zh: '约翰福音',
    bookCategory: 'Gospels',
    type: 'bible',
    slug: 'john',
  },
  bookActs: {
    en: 'Acts',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'acts',
  },
  bookRomans: {
    en: 'Romans',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'romans',
  },
  book1corinthians: {
    en: '1 Corinthians',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-corinthians',
  },
  book2corinthians: {
    en: '2 Corinthians',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-corinthians',
  },
  bookGalatians: {
    en: 'Galatians',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'galatians',
  },
  bookEphesians: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'ephesians',
  },
  bookPhilippians: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'philippians',
  },
  bookColossians: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'colossians',
  },
  book1thessalonians: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-thessalonians',
  },
  book2thessalonians: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-thessalonians',
  },
  book1timothy: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-timothy',
  },
  book2timothy: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-timothy',
  },
  bookTitus: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'titus',
  },
  bookPhilemon: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'philemon',
  },
  bookHebrews: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'hebrews',
  },
  bookJames: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'james',
  },
  book1peter: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-peter',
  },
  book2peter: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-peter',
  },
  book1john: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '1-john',
  },
  book2john: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '2-john',
  },
  book3john: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: '3-john',
  },
  bookJude: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'jude',
  },
  bookRevelation: {
    en: '',
    zh: '',
    bookCategory: '',
    type: 'bible',
    slug: 'revelation',
  },
};
